### ISSUE TITLE
orator cli doesn't work on windows

### ISSUE THREAD

**Issue by yos-virtus** [sdispater/orator#37] opened 2016-02-08 18:53 UTC
I tryed to execute `orator make:migration create_example_table` on my freshly created virtualenv, but it says that this command can't be executed. I also tryed .\Scripts\orator. The same thing.
Steps that I followed:

1. Created vitual enviroment 

2. Installed orator

3. Activated my virtual env

4. Created orator.xml 

5. Run orator make:migration create_example_table

**Comment by sdispater** [comment] 2016-02-08 20:33
What's the actual error message?

**Comment by yos-virtus** [comment] 2016-02-09 07:32
"orator" not recognized as an internal or external command, operable program or batch file.

**Comment by yos-virtus** [comment] 2016-02-09 07:38
Here is what in my orator.yml 
![orator](https://cloud.githubusercontent.com/assets/7825897/12910183/3b6c1244-cf19-11e5-9ded-fd15e8848dbf.png)

**Comment by sdispater** [comment] 2016-02-09 15:07
OK. That's what I thought.

Orator is using [Cleo](https://github.com/sdispater/cleo) for all commands, but Cleo has not been properly tested on Windows yet.

I will see if I can find out where the problem is.

**Comment by yos-virtus** [comment] 2016-02-09 17:22
Ok. That would be nice. 
Great ORM/AR by the way. Eloquent is great but eloquent(i mean orator) for python mmmmm.

**Comment by sdispater** [comment] 2016-02-09 22:53
Thanks for the kind words :smiley: 

So, it appears that there were two issues actually:

* Cleo was not working well on Windows. I just released a new version compatible with Windows.
* The way the `orator` script was installed did not work on Windows. It has been fixed on the `develop` branch.

So can you test the `develop` branch (`pip install "git+https://github.com/sdispater/orator.git@develop#egg=orator" -U`) to see if it's working for you?

**Comment by yos-virtus** [comment] 2016-02-10 07:30
I'll try it.

**Comment by yos-virtus** [comment] 2016-02-10 08:07
Ok. orator command is responding now but when i tryed this `orator make:migration create_users_table --table=users --create` it gave me following error:
![image](https://cloud.githubusercontent.com/assets/7825897/12941744/4d176048-cfe6-11e5-8151-6871c318f4aa.png)

**Comment by sdispater** [comment] 2016-02-10 15:52
The `Invalid format string` was caused by a typo in the code but only on Windows. I just pushed a fix on the `develop` branch.

For your second error, I can't reproduce it. What's the content of your `orator.py` file?

**Comment by yos-virtus** [comment] 2016-02-10 16:09
Here is what in my ** orator.py**
![orator_testing_2](https://cloud.githubusercontent.com/assets/7825897/12953000/b5e7a1c6-d029-11e5-8309-40bac8f0c101.jpg)

**Comment by sdispater** [comment] 2016-02-10 17:22
I still can't reproduce the error when using an `orator.py` configuration file.

For the time being, I advise you to keep using the `orator.yml` file.

**Comment by yos-virtus** [comment] 2016-02-10 17:47
Thanks. It works now. As of the orator.py I will try on a different machine maybe it related to some settings on my current PC. I installed python 2.7 not so long ago for it's necessary when you pull/install Laravel-Elixir and it's dependencies.

**Closed** 2016-03-30 20:25 UTC
