### ISSUE TITLE
Different timezone when get one model through different ways

### ISSUE THREAD

**Issue by Neschur** [sdispater/orator#161] opened 2017-04-06 11:03 UTC
VERSION: 0.9.5

response = Response.create()
print(response.id, response.created_at)

response = Response.order_by('id', 'DESC').first()
print(response.id, response.created_at)

OUTPUT:
513 2017-04-06T**11**:00:42.035452+**00:00**
513 2017-04-06T**14**:00:42.035452+**00:00**

My local time: UTC+3:00

**Comment by sdispater** [comment] 2017-04-06 16:07
Are you using PostreSQL by any chance? I can reproduce the problem only with a PostgreSQL backend.

**Comment by Neschur** [comment] 2017-04-06 19:53
Yes, I use PostreSQL 9.5.6

**Comment by sdispater** [comment] 2017-04-06 20:07
Ok. It seems that since the timestamp column contains a timezone information (offset) when the `INSERT` query is executed each the column value is actually casted to `timestamptz` by `psycopg2` which give a value in the current server timezone.

In your example, it would be:

```sql
INSERT INTO "responses" ("created_at") VALUES ('2017-04-06T11:00:42.035452+00:00'::timestamptz)
```

and since you are in UTC+3 the actual value is `14:00:42.035452+03:00`. However, timestamps column are without timezone in Orator so the timezone information is lost.

When you retrieve the column Orator assumes UTC giving the wrong result.

**Comment by Neschur** [comment] 2017-04-16 09:32
I seems it is a bug? Why it doesn't marked as a bug?

**Comment by sdispater** [comment] 2017-04-16 19:28
Yes, it's a bug. And it should be fixed on master.  You can test if you want.

**Closed** 2017-05-16 20:36 UTC
Labels: bug
